services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: file:/app/data/prod.db
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
    volumes:
      - lottery-data:/app/data
    command: sh -c "npx prisma db push && npm run start"
    restart: unless-stopped

volumes:
  lottery-data:
